### ISSUE TITLE
Change HTML Text Color?

### ISSUE THREAD

**Issue by Zackery** [Yummygum/city-lights-sublime#10]
Hi there, I was wondering if it was possible to change the HTML text color from this blue/gray color to a light/white, more distinguishable color. Thanks!

[HTML Example](https://i.zelakto.tv/images/KmOQ.png)

**Comment by noudadrichem** [comment]
Hi @Zelakto,

This is a design choice. If you want to change things to the theme I recommend downloading the theme and change it yourself. 

I wholeheartedly recommend reading the license before sharing it.
