### ISSUE TITLE
Additional features to notepad++ workspace menu

### ISSUE THREAD

**Issue by DanielAzzam** [Yummygum/city-lights-sublime#17]
![image](https://github.com/Yummygum/city-lights-sublime/assets/17107884/b5445e08-b3d9-4021-8a9d-a77cf3ca3b57)

Visual Studio Code has the following valuable features in its workspace (new file, new folder, rename , delete ) 
Is it feasible to add those to notepad ++?

attached is a screenshot comparing both editors 

Thank you 
Daniel

**Comment by DanielAzzam** [comment]
Any feedback ?

**Comment by zoeyfrisart** [comment]
Hi @DanielAzzam Thank you for your issue, however I believe you have probably created this at the wrong repository. This is a theme for Sublime text (and other editors such as Atom & VSCode). If you want a feature to be added to Notepad++ you should open up an issue in the notepad++ repository here: https://github.com/notepad-plus-plus/notepad-plus-plus/issues

For now I wish you a great day. If we misunderstood what you meant by this issue please let us know
