### ISSUE TITLE
Command Palette

### ISSUE THREAD

**Issue by mauroreisvieira** [Yummygum/city-lights-sublime#3]
Hi, great work... Theme is very nice... But when go to Command Palette is be a little awkward.

![screen shot 2018-01-16 at 12 07 48](https://user-images.githubusercontent.com/3084774/34988609-2a404e1a-fab7-11e7-8f57-aac69e7c5af8.png)

**Comment by noudadrichem** [comment]
Hi @maurovieirareis, 

We'll take a look at this. 😊

**Comment by noudadrichem** [comment]
This is fixed in the next release, the fuzzy finder now also has a 'selected' state.
