### ISSUE TITLE
Color Scheme

### ISSUE THREAD

**Issue by mauroreisvieira** [Yummygum/city-lights-sublime#4]
Hi again, its not a real issues, but i think this is interessant if you change some colors in the theme like:

**SCSS Variables:**

![screen shot 2018-01-16 at 16 42 19](https://user-images.githubusercontent.com/3084774/35000929-8f9a9f92-fadd-11e7-9ded-72cb03e6aa61.png)

**JavaScript / Typescript eg: Scope like "this.element" or cast lioke "<HTMLElement>**

![screen shot 2018-01-16 at 16 41 39](https://user-images.githubusercontent.com/3084774/35000902-7d3dca36-fadd-11e7-80e2-ad63a50b059d.png)

**Git Gutter Color:**

![screen shot 2018-01-16 at 16 42 28](https://user-images.githubusercontent.com/3084774/35001001-bbcaacba-fadd-11e7-94d0-2c1e7f207f7b.png)

Is more nice, if have have some deleted line or removed line put colors like, red or green to make a different for developer.

**Comment by noudadrichem** [comment]
Hi @maurovieirareis,

Thanks for reporting this, it's important for us people do this, thanks!
I'll take a look at this. What package are you using for the scss highlighting?

Sincerely

**Comment by mauroreisvieira** [comment]
Hi @noudadrichem for SCSS is https://packagecontrol.io/packages/SCSS.

Thanks for your work! 
I love this theme.

**Comment by noudadrichem** [comment]
Hi @maurovieirareis really glad you like the theme!

I have fixed some things in the next release.
If you want git gutter to have other colors you can change them yourself in your user settings or make a PR with the changes.

Sincerely
