### ISSUE TITLE
Recent files list don't have hover styling

### ISSUE THREAD

**Issue by imolorhe** [Yummygum/city-lights-sublime#7]
First off, just started using this theme in sublime and I'm loving it!

However, I have a major painpoint at the moment. Whenever I access the recent files list (i.e. `Cmd + P` and then pressing the down arrow to browse the list), there is no hover styling. There were some cases where the hover styling showed (by changing the font color to a lighter color, but with no background color change), but those were very rare. Most of the time there was no styling at all.
I now have to be looking at the highlighted tabs and trying to correspond it with the items in the list, which is a painful process to have to do.

**Comment by noudadrichem** [comment]
Hi @imolorhe,

This is a known bug, we're working on it. Thanks for reporting!

Sincerely

**Comment by imolorhe** [comment]
When is the fix for this issue going to be pushed?

**Comment by noudadrichem** [comment]
Fixed in the next release. 🎉
