### ISSUE TITLE
Vim port

### ISSUE THREAD

**Issue by agreco** [Yummygum/city-lights-sublime#8]
Hey really digging this scheme, any chance of a Vim port?

**Comment by al3xtjames** [comment]
I used [Coloration](https://github.com/sickill/coloration) to convert the TextMate theme, which [mostly worked](https://github.com/al3xtjames/dotfiles/blob/master/.config/nvim/colors/City-Lights.vim) (there are some elements which are using the default colors - if anyone could help fix this, it would be appreciated). The Airline theme for [vim-one](https://github.com/rakr/vim-one) is adaptive and seems to match well.

**Comment by noudadrichem** [comment]
Hi @agreco,

Glad you like the theme! We'll take a look at this!
Thanks for the suggestions @al3xtjames 

Sincerely
