### ISSUE TITLE
Files and folder icons at the same level should be aligned

### ISSUE THREAD

**Issue by imolorhe** [Yummygum/city-lights-sublime#9]
Hello.

In the sidebar, the icons for the files and folders should be aligned. Currently, the files are indented and the folders don't have arrows showing when they are open. Because of that, the files look like they are within the last folder on the same level.

**Comment by noudadrichem** [comment]
Hi @imolorhe,

Can you maybe attach an image of what you mean? The indicator for the open/closed folder is in the icon itself, where open is: https://d.pr/i/5vw5Gh and closed is https://d.pr/i/H3Zzum.

The indentation should look like this: https://d.pr/i/uHzGl7

**Comment by imolorhe** [comment]
In the screenshot, the folder "header" is in the same root level as the files but they are indented and look like they are inside the "header" folder.

![screen shot 2018-01-29 at 2 39 33 pm](https://user-images.githubusercontent.com/4608143/35513124-4b0994c6-0502-11e8-9ed0-88a27d3e3919.png)

**Comment by noudadrichem** [comment]
Ah, oke I see the issue! Thanks for reporting!

**Comment by imolorhe** [comment]
When is the fix for this issue going to be pushed? It's really beginning to affect my workflow.

**Comment by noudadrichem** [comment]
It's harder to fix than expected. I have some questions open to other developers. I hope I can fix it asap.

**Comment by noudadrichem** [comment]
Hi @imolorhe,

I can say It'll be fixed in the next release! 

😊
